# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmershelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=120)),
                ('crop_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=120)),
                ('farm_description', models.TextField()),
                ('farmers_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershelp.Farmers')),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120)),
                ('field_description', models.TextField()),
                ('crop_id_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmershelp.Crops')),
                ('farm_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershelp.Farms')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=120)),
                ('season_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='crops',
            name='seasons_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershelp.Seasons'),
        ),
    ]
