# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmershelp', '0002_auto_20171004_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='FarmerName',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
