# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmershelp', '0003_auto_20171004_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='crop_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmershelp.Crops'),
        ),
    ]
